name: Test, Build, and Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  test:
    name: Run tests.
    runs-on: ubuntu-latest
    steps:
    - name : Install dependencies.
      run: sudo apt-get install cc65
    - uses: actions/checkout@v4
    - name: make test
      run: make test
  build:
    name: Build ROM.
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies.
      run: sudo apt-get install cc65
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload ROM.
    - uses: actions/upload-artifact@v4
      with:
        name: rom
        path: bin/front_office.nes
  publish:
    name: Publish ROM.
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout publish site.
    - uses: actions/checkout@v4
      with:
        repository: "puchiedarcy/puchiedarcy.github.io"
    - name: Download ROM.
    - uses: actions/download-artifact@v4
      with:
        name: rom
    - name: Commit ROM.
      run:
        git add front_office.nes
        git commit -m "Publishing newest ROM."
        
