name: Test, Build, and Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name : Install cc65
      run: sudo apt-get install cc65
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: make test
    - name: Upload test report card
      uses: actions/upload-artifact@v4
      with:
        name: test_report_card
        path: bin/front_office_test_report_card.json
  perf:
    name: Performance
    runs-on: ubuntu-latest
    steps:
    - name : Install cc65
      run: sudo apt-get install cc65
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run perf
      run: make perf
    - name: Upload perf report card
      uses: actions/upload-artifact@v4
      with:
        name: perf_report_card
        path: bin/front_office_perf_report_card.json
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install cc65
      run: sudo apt-get install cc65
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Make ROM
      run: make
    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: rom
        path: bin/front_office.nes
    - name: Upload space used report
      uses: actions/upload-artifact@v4
      with:
        name: space_used_report
        path: bin/front_office_space_used.json
  publish:
    name: Publish
    needs: 
    - test
    - perf
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download test report card
      uses: actions/download-artifact@v4
      with:
        name: test_report_card
        path: pub/
    - name: Download perf report card
      uses: actions/download-artifact@v4
      with:
        name: perf_report_card
        path: pub/
    - name: Download space used report
      uses: actions/download-artifact@v4
      with:
        name: space_used_report
        path: pub/
    - name: Download ROM
      uses: actions/download-artifact@v4
      with:
        name: rom
        path: pub/
    - name: Compress
      run: tar -czvf github-pages pub/*
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'pub/'
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
