name: Test, Build, and Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  test:
    name: Run tests.
    runs-on: ubuntu-latest
    steps:
    - name : Install dependencies.
      run: sudo apt-get install cc65
    - name: Checkout code.
      uses: actions/checkout@v4
    - name: Run tests.
      run: make test
  build:
    name: Build ROM.
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies.
      run: sudo apt-get install cc65
    - name: Checkout code.
      uses: actions/checkout@v4
    - name: Make ROM.
      run: make
    - name: Upload ROM.
      uses: actions/upload-artifact@v4
      with:
        name: rom
        path: bin/front_office.nes
  publish:
    name: Publish.
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code.
      uses: actions/checkout@v4
    - name: Download ROM.
      uses: actions/download-artifact@v4
      with:
        name: rom
        path: docs/
    - name: Compress site.
      run: tar -czvf github-pages docs/*
    - name: Publish to GitHub Pages.
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'pub/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
